import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';

// Load environment variables from .env file
dotenv.config();



const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const outdir = "build";

const copyFileLog = (source, destination) => {
    console.log(`Attempting to copy: ${source} -> ${destination}`);
    if (!fs.existsSync(source)) {
        console.error(`Source file not found: ${source}`);
        return;
    }
    try {
        fs.copyFileSync(source, destination);
        console.log(`SUCCESS: Copied ${source}`);
    } catch (err) {
        console.error(`FAILED to copy ${source}:`, err);
    }
};

const copyToPluginDir = () => {
    console.log("\n--- Executing copyToPluginDir function ---");
    const pluginDir = process.env.PLUGIN_DEST_PATH;

    if (!pluginDir) {
        console.log("SKIPPED: PLUGIN_DEST_PATH is not defined in .env file.");
        return;
    }
    console.log(`Found PLUGIN_DEST_PATH: ${pluginDir}`);

    if (!fs.existsSync(pluginDir)) {
        console.log(`Destination directory does not exist. Attempting to create: ${pluginDir}`);
        try {
            fs.mkdirSync(pluginDir, { recursive: true });
            console.log(`SUCCESS: Created plugin directory: ${pluginDir}`);
        } catch (err) {
            console.error(`FAILED to create plugin directory:`, err);
            return;
        }
    } else {
        console.log("Destination directory already exists.");
    }

    copyFileLog(path.join(outdir, 'main.js'), path.join(pluginDir, 'main.js'));
    copyFileLog('manifest.json', path.join(pluginDir, 'manifest.json'));
    if (fs.existsSync('styles.css')) {
        copyFileLog('styles.css', path.join(pluginDir, 'styles.css'));
    }
    
    console.log("--- Finished copyToPluginDir function ---\
");
};

(async () => {
    try {
        const context = await esbuild.context({
            banner: {
                js: banner,
            },
            entryPoints: ["src/main.ts"],
            bundle: true,
            external: [
                "obsidian",
                "electron",
                "@codemirror/autocomplete",
                "@codemirror/collab",
                "@codemirror/commands",
                "@codemirror/language",
                "@codemirror/lint",
                "@codemirror/search",
                "@codemirror/state",
                "@codemirror/view",
                "@lezer/common",
                "@lezer/highlight",
                "@lezer/lr",
                ...builtins
            ],
            format: "cjs",
            target: "es2018",
            sourcemap: prod ? false : "inline",
            treeShaking: true,
            outfile: path.join(outdir, 'main.js'),
            charset: "utf8",
        });

        if (prod) {
            console.log("Starting production build...");
            await context.rebuild();
            console.log("Build finished.");
            copyToPluginDir();
            process.exit(0);
        } else {
            console.log("Starting development watch...");
            await context.watch();
        }
    } catch (e) {
        console.error("Build process failed:", e);
        process.exit(1);
    }
})();
